### ISSUE TITLE
Postgrex expected a binary, got %Geo.Point

### ISSUE THREAD

**Issue by Virviil** [bryanjos/geo#70] opened 2017-06-10 17:35 UTC
This query is working:
```
INSERT INTO "bookmarks" ("address","bookmark_type","description","is_active","is_delete","latlng","tag","uid","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "id" ["adi", "private", "testing", true, false, %Geo.Point{coordinates: {26.7885576, 75.8270401}, srid: 4326}, "test1 test2 test3", "2ffce5f2e79a4f8c917fc58591260cdb80011f6d", {{2017, 6, 10}, {17, 30, 46, 127816}}, {{2017, 6, 10}, {17, 30, 46, 134318}}]
```

while this one returns error:
```
SELECT b0."id", b0."uid", b0."tag", b0."description", b0."address", b0."bookmark_type", b0."is_active", b0."is_delete", b0."latlng", b0."inserted_at", b0."updated_at" FROM "bookmarks" AS b0 WHERE (b0."bookmark_type" = 'public') AND (ST_Within(b0."latlng",ST_Buffer($1, $2, 8))) AND ((b0."is_active" = TRUE) AND (b0."is_delete" != TRUE)) ORDER BY b0."updated_at" DESC LIMIT $3 OFFSET $4 [%Geo.Point{coordinates: {26.7885576, 75.8270401}, srid: 4326}, 1.0, 10, 0]
```

So, I'm totally confused. It seems to me that potgrex in both cases should either work or not work - because either cast or not cast to binary.

May be I'm mising something in the configuration, or you can navigate me where should I dig deeper to see where is the problem?

**Comment by bryanjos** [comment] 2017-06-11 16:27
@Virviil I'm not sure either with the information given. It may be a configuration problem. Are the two queries run in the same mix environment? Is there a simpler query you could run that shows it working or not working?

**Comment by Virviil** [comment] 2017-06-11 17:22
Yep, both queries in one session of `mix phoenix.server`

**Comment by Virviil** [comment] 2017-06-12 07:19
I can provide you any information, just don't know which

**Comment by bryanjos** [comment] 2017-06-15 13:30
@Virviil is that the query the Ecto runs? If so could you show me your Ecto query if possible?

**Comment by Virviil** [comment] 2017-06-15 15:02
No problem.

**SELECT Request**
```
Repo.all(
    from b in Bookmark,
    where: b.bookmark_type == "public",
    where: st_within(b.latlng, st_buffer(^point, ^radius, 8)),
    where: b.is_active == true and b.is_delete != true,
    order_by: [desc: b.updated_at],
    offset: ^offset,
    limit: ^limit,
    select: b
)

**INSERT Request **
Just populating changeset, one of the params is `%Geo.Point{}`, and then `Repo.insert`

**Comment by bryanjos** [comment] 2017-06-30 16:07
@Virviil sorry for the delayed response. I'm not sure what the issue is from looking at it. As far as I can tell from the SQL and from the Ecto query, it all looks correct. It may be a bug here, but not sure. Could also be something with Postgrex, but let's make sure first. What happens if you replace the called to `st_within` and `st_buffer` with fragments that call the underlying PostGIS functions?

**Comment by Virviil** [comment] 2017-07-01 18:17
I tried to recreate the same bug with different versions of Postgrex - and
it still appears. After that I've tried to recreate the bug on another
computer - and it doesn't appear.
After that I found workaround - manually encode the Geo.Point struct into
string with Geo.Wrk.encode. And everything works.
So, I think that the problem is with some of the deps, but I totally don't
know which one.

**Comment by bryanjos** [comment] 2017-07-01 21:38
Glad you were able to find a workaround. When I have some time I'll try to reproduce this and if I can I'll try to fix it.

**Comment by bryanjos** [comment] 2018-01-28 14:58
Going to close this since there was a workaround and nothing has came up since

**Closed by bryanjos** 2018-01-28 14:58 UTC
